version: '3.8'

services:
  test:
    command: sh -c "npm install && npm run test"
    image: node:18-alpine
    environment:
      MILL_KAPPA_JOURNAL_ID: some-service-id
      MILL_KAPPA_MONGO_DB: some-databse
      MILL_KAPPA_MONGO_URI: mongodb://mongo:27017/
    volumes:
      - ./:/app
    working_dir: /app

  mongo:
    image: bitnami/mongodb:6.0
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MONGODB_REPLICA_SET_MODE: primary
    volumes:
      - mongo-volume:/data/db

  mongo-admin:
    image: mongo-express:1.0.0-alpha.4
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    ports:
      - 8081:8081
    restart: always # ! Mongo cold starts prevent connections on first try

volumes:
  mongo-volume: {}
